name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
  NODE_ENV: production
  NEXT_PUBLIC_GEONAMES_USERNAME: explorimentalist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Clear npm cache
        run: npm cache clean --force
      
      # Add cache for Next.js build
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            out
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev typescript@5.6.3 @types/node@20.17.6

      - name: Verify TypeScript
        run: npx tsc --version

      - name: Build project
        run: |
         npm run clean
         NODE_ENV=production npm run build
      
        env:
          NEXT_PUBLIC_GEONAMES_USERNAME: explorimentalist
          CI: true
          
      - name: Upload artifact
        if: success()
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4